### ISSUE TITLE
GeoObject が正しい高度に表示されず、高度ほぼ 0 付近に表示される事がある

### ISSUE THREAD

**Issue by KouichiAraki** [godai-kaihatsu/gondwana#17]
GeoObject APIのHello Worldに記載されている3コマンドを入力し，緯度経度・高度・地上方位を「期待される結果」と同様にしましたが，G4上に三角が表示されません．
![default](https://user-images.githubusercontent.com/34147571/33464690-f623e708-d686-11e7-8405-0e876b8f40dd.JPG)

環境は以下の通りです．
G4のバージョン：G4-preview-2d
コマンド実行環境：bash on ubuntu on windows
OS：Windwos 10 Pro 64bit
メモリ：8GB 
GPU：Geforce GTX 960
GPUメモリ：2GB

以下は実行結果です．

```sh
curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id": null, "method": "GeoObject.New" }'
HTTP/1.1 200 OK
Content-Length: 52
Content-Type: application/json
{
        "jsonrpc": "2.0",
        "id": null,
        "result": 0
}

curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id":null, "method": "GeoObject.SetVertexGlobal", "params": { "id": 0, "vertices": [ 200.0, 43.062096, 141.354376, 200.0, 43.067096, 141.349376 , 200.0, 43.067096, 141.359376 ] } }'
HTTP/1.1 200 OK
Content-Length: 55
Content-Type: application/json
{
        "jsonrpc": "2.0",
        "id": null,
        "result": null
}

curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id":null, "method": "GeoObject.SetIndex", "params": { "id": 0, "indices": [ 0, 1, 2, 0, 2, 1 ] } }'
HTTP/1.1 200 OK
Content-Length: 55
Content-Type: application/json
{
        "jsonrpc": "2.0",
        "id": null,
        "result": null
}
```

**Comment by usagi** [comment]
再現しませんでした。確実な再現方法・環境の特定をお願いします。

![image](https://user-images.githubusercontent.com/115972/33467891-6c72566a-d69b-11e7-81ee-2002fab89b49.png)

```sh
  << curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id": null, "method": "GeoObject.New" }'
HTTP/1.1 200 OK
Content-Length: 52
Content-Type: application/json

{
        "jsonrpc": "2.0",
        "id": null,
        "result": 0
}%
```

```sh
  << curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id":null, "method": "GeoObject.SetVertexGlobal", "params": { "id": 0, "vertices": [ 200.0, 43.062096, 141.354376, 200.0, 43.067096, 141.349376 , 200.0, 43.067096, 141.359376 ] } }'

HTTP/1.1 200 OK
Content-Length: 55
Content-Type: application/json

{
        "jsonrpc": "2.0",
        "id": null,
        "result": null
}%
```

```sh
  << curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id":null, "method": "GeoObject.SetIndex", "params": { "id": 0, "indices": [ 0, 1, 2, 0, 2, 1 ] } }'

HTTP/1.1 200 OK
Content-Length: 55
Content-Type: application/json

{
        "jsonrpc": "2.0",
        "id": null,
        "result": null
}%
```

**Comment by KouichiAraki** [comment]
G4-preview-2d/G4/Saved/Config/WindowsNoEditor/Game.iniに以下を記述したら，下図のように三角形が表示されました．三角形が表示されなかったのは直下LODが12となっていたことが原因だと思われます．

![default](https://user-images.githubusercontent.com/34147571/33755409-f6e4b6c4-dc33-11e7-8f6d-366de87e817b.JPG)
```
```ini
[/Script/G4.ProceduralPlanet]
lod0_min=0
lod0_max=0
pmc_pool_initial_count=0
enable_adjacency_cells=False
```
また，以下の環境においても三角形が表示されることを確認しました．
G4のバージョン：G4-preview-2d
コマンド実行環境：Cygwin Terminal
OS：Windows 7 Pro 64bit
メモリ：32GB
ストレージ：SSD
GPU：Core-i7 6700KのiGPU

**Comment by usagi** [comment]
@KouichiAraki 

なるほど…、もしかするとエグザンプルの triangle の頂点が地形に埋もれて見えなかったのかもしれませんね。あるいは GeoObject の頂点座標の取り扱いに何らかのバグがあり設定よりも低い高度に頂点が生成されているという可能性、この2つを想起できました。

後ほど開発環境でこの推量に基づいた再現や調査を行い、結果をこちらに追記、再現性と必要な対応が明らかとなればその対処を進めます。追加の検証情報ありがとうございます。

**Comment by usagi** [comment]
```sh
curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id": null, "method": "GeoObject.New" }'
curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id": null, "method": "GeoObject.SetVertexLocal", "params": { "id": 0, "vertices": [ 0.0, 0.0, 0.0, -1000, -1000, 0, 1000, -1000, 0, -1000, 1000, 0, 1000, 1000, 0 ] } }'
curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id": null, "method": "GeoObject.SetUV", "params": { "id": 0, "uvs": [ 0.5,0.5, 0,0, 1,0, 0,1, 1,1 ] } }'
curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id": null, "method": "GeoObject.SetLocationByAltLatLon", "params": { "id": 0, "location": [ 1898.0, 42.826667, 140.811389 ] } }'
curl -Ss -i http://127.0.0.1:50080/api/json-rpc-2.0/ -X POST --data '{ "jsonrpc": "2.0", "id": null, "method": "GeoObject.SetIndex", "params": { "id": 0, "indices": [ 0,1,2, 0,3,1, 0,2,4, 0,4,3, 0,2,1, 0,1,3, 0,4,2, 0,3,4 ] } }'
```

羊蹄山、山頂に併せて矩形に見える GeoObject を展開するコードを試したところ、なぜか矩形が高度 87.70 m 付近に展開されるバグを確認した。

![image](https://user-images.githubusercontent.com/115972/33923107-8ec614e2-e012-11e7-9e5e-344c435b6a46.png)

**Comment by usagi** [comment]
問題の現象が発生する原因を特定し、修正した。この修正は 4.0.0.10 に取り込む。

![image](https://user-images.githubusercontent.com/115972/33923685-d9687a14-e015-11e7-918c-d9ca882f8f41.png)

**Comment by usagi** [comment]
羊蹄山山頂にデフォルトテクスチャーの矩形を表示

高度 1500 m から仰角で眺めた絵:

![image](https://user-images.githubusercontent.com/115972/33923918-06fe269e-e017-11e7-98b3-79dc941b1ac8.png)

高度 1.88 km ≃ ほぼ山頂、若干下から。地形システムの山頂に地物システムの矩形の高度がぴったりと一致している

![image](https://user-images.githubusercontent.com/115972/33923956-27ce6104-e017-11e7-9cd7-3d39a31a67f4.png)

高度 3.06 km より見下ろし

![image](https://user-images.githubusercontent.com/115972/33924015-74de49d2-e017-11e7-8372-c62d7d42020d.png)

**Comment by usagi** [comment]
@KouichiAraki さん、 CBT 参加と問題のご報告を頂きありがとうございました。↑のように問題を再現、実装上のバグを確認し、修正対応を次回の CBT リリース 4.0.0.10 へ含める事ができました。引き続き CBT へのご参加、お気づきの問題などありましたらご報告頂ければ幸いです。ありがとうございました 👍
