### ISSUE TITLE
GeoObject システムに GeoJSON をロードする API が欲しい / 実装ステップ2: LineString へ対応

### ISSUE THREAD

**Issue by usagi** [godai-kaihatsu/gondwana#41]
relative: https://github.com/godai-kaihatsu/gondwana/issues/23#issuecomment-353082916

**Comment by KouichiAraki** [comment]
LineStringの実装はいつ頃になりそうでしょうか？
ある方が業務の社外での説明会でCAD図面を地図にマッピングして3次元で説明できたらいいなと言っておりました．
なお，図面のdxfからgeojsonへの変換は済んでいます．

**Comment by usagi** [comment]
#65 に関連して本件を HUD レベルで実装する案について検討したのでメモを残す。

結論: HUD レベルでは GeoObject の代表ロケーションの表示に留め、 points, lines, 等は GPU 処理でメインビューへ描画。

主な理由:

G4 の実装都合、 HUD レベルの実装は頂点数がそれほど多くないならば CPU 負荷に問題は生じ難く、ソースデータの編集への対応も容易だが、用途として "県境" のような複雑で多くの頂点を扱いたいであろう要求が予想されるため、つまり大量の頂点変換処理に GPU を用いた方が良いだろうと考えられる。HUD実装でも計算をGPU処理する事は可能だが実装が複雑化し消費リソースも増える割には利点もない。
