### ISSUE TITLE
dev'http_api'referenceに記載されている「GetProducttName」がタイポである

### ISSUE THREAD

**Issue by KouichiAraki** [godai-kaihatsu/gondwana#46]
「GetProducttName」と記載されているが，tが1つ多くないか？
dev'http_api'reference'GetProductNameには「GetProductName」と記載されている．

**Comment by usagi** [comment]
https://github.com/godai-kaihatsu/gondwana/wiki/dev'http_api'reference

current:

![image](https://user-images.githubusercontent.com/115972/34699975-c7f38b52-f523-11e7-99ab-f2cb9a943191.png)

状況を確認しました。

**Comment by usagi** [comment]
current-source:

![image](https://user-images.githubusercontent.com/115972/34700017-f925aebc-f523-11e7-91b2-db82f641fa6b.png)

目次ページの表記のみ間違えておりリンク先のミスは無い事を確認。

**Comment by usagi** [comment]
修正完了:

![image](https://user-images.githubusercontent.com/115972/34700055-274d31b6-f524-11e7-9b6f-d12940051794.png)

@KouichiAraki ドキュメントバグの報告ありがとうございました。 👍
