### ISSUE TITLE
キーボードのEを押し続けても高度-7.08mから上昇しない

### ISSUE THREAD

**Issue by KouichiAraki** [godai-kaihatsu/gondwana#53]
環境はG4-preview-4aです．
１．G4起動
２．キーボードのQを押し続けて高度が-22.01mにする．
（この時ロボットは地表面に立っている）
![default](https://user-images.githubusercontent.com/34147571/34765805-d2f7cd7a-f635-11e7-9c8f-93f3a5074003.JPG)
３．キーボードのEを押し続けて上昇しても-7.08m以上上昇しない．
![1](https://user-images.githubusercontent.com/34147571/34765997-5cbc301e-f636-11e7-84d5-a617912c3afd.JPG)

**Comment by usagi** [comment]
状況については後ほど詳しく再現実験と確認を行います。

さしあたりの応急対応が必要な場合、 `/` キーまたはメインメニューから座標指定移動メニューを呼び出し、 altitude のみ 1000 など適当な高度を入力して "脱出" 可能かもしれません。

現象の推量としては、本来通常動作では LOD=0 での地上付近の動作は想定外のため、マネキン（注視点）の位置に隣接する最近の地形タイル頂点の高度群に対して、マネキンの足元にできる地上の高度（隣接する地形タイルの頂点の密度が想定外に疎な場合、G4はWGS84モデルに基いた球面の地上を生成するため、地球が擬似的な球ではなく明らかに多角形化する）が疎な頂点による面にはめり込んだ状態が発生する事が一因のような気がします。

なお、弊社と開発者の出張都合により、対応は 2018-01-15 以降となります。

**Comment by usagi** [comment]
この問題は通常使用の想定される高度とLOD条件でも `/` `G` による長距離の移動直後などに発生する事があるようだ。

**Comment by usagi** [comment]
再現性の高い例: 「羊蹄山」付近 2000m LOD=13 → `/` → 「銀山小学校」

地上の判定が奇妙な状態となるのか、ジャンプや飛行モードの処理に問題があるのか、飛べずに地表付近までゆっくりと落下する状態が発生する。

**Comment by usagi** [comment]
4.0.0.18 でそもそも地上モードを廃止し注視点の標高の設定方法を変更したため原理的に発生しなくなった。完了。
