### ISSUE TITLE
「地表の地図画像の設定」においてタイルサービスが利用できない。

### ISSUE THREAD

**Issue by KouichiAraki** [godai-kaihatsu/gondwana#75]
Wikiに「地表 / 地図画像タイルメニュー」について書かれていますが、G4-4.0.0.16ではタイルサービスが利用できないのでしょうか？
＜タイルサービスの追加＞の下にあるプルダウンには何もありません。
なお、下図のように更新ボタンを押してたら「報告：マテリアルタイルサービス群を再読み込みしました。」と表示されます。

![1](https://user-images.githubusercontent.com/34147571/36521226-06019128-17d9-11e8-8cda-5769b7e4f3a4.JPG)

**Comment by usagi** [comment]
使えます。 screenshot から推量するに、 tile_service に定義を入れていなだけではないかと思います。 

- https://github.com/godai-kaihatsu/gondwana
- https://github.com/godai-kaihatsu/gondwana/wiki/pow'tile_service'edit

この github リポジトリーに定義ファイルのサンプルがあり、その旨は開発ブログの Release Note でも案内しています。CBT はインストーラーやフルパッケージでの一般ユーザー向けの提供は目的ではないため、注意事項を丁寧に毎度解説していません。

また、将来の G4 においても G3 のように膨大なタイル定義を標準搭載するつもりはありません。理由は installer の仕事だからです。 CBT 版は installer が必要な一般ユーザー向けにはまだ提供していないものです。一般ユーザーは installer がオプションとして幾らかの選択肢からユーザーが目的に併せて選択した結果に基いて前述の repos から定義を installler によって download され、配置されるでしょう。

少なくとも CBT から installer を提供できるだけの開発リソースの余裕は残念ながらありません。 CBT ユーザーは Release Note 群を追い、 WIKI を解読しながら、手作業で必要な tile_service 定義を配置先の G4 CBT のディレクトリーへ手作業で配置して下さい。

**Comment by KouichiAraki** [comment]
申し訳ありません、記載されたWikiを確認していませんでした。
このWikiに従って、行います。
アドバイスありがとうございます。

**Comment by usagi** [comment]
@KouichiAraki こちらこそ、ユーザーサポートを丁寧にできるだけのリソースが開発には無く CBT ユーザーにおかれましても不便や操作についての疑問、誤解等が発生しやすい状況についてお詫びいたします。特に CBT ではこうしたご不便に今後も幾つか遭遇されるかもしれませんが、今後とも CBT 版のテスト、開発へご協力頂ければ幸いです。
